### ISSUE TITLE
Missing libEGL.so.1 / libuuid.so.1

### ISSUE THREAD

**Issue by bndlfm** [bndlfm/OpenMW-VR_Nix#1]
Tried adding libglvnd and libuuid to buildInputs, runtimeDependencies, propagatedBuildInputs, etc. 

`export LD_LIBRARY_PATH=$(nix build --print-out-paths --no-link nixpkgs#libGL)/lib` lets it find libEGL.so.1, but then complains about libuuid. 

Trying the same trick i.e. `export LD_LIBRARY_PATH=$(nix build --print-out-paths --no-link nixpkgs#libGL)/lib:$(nix build --print-out-paths --no-link nixpkgs#libuuid)` doesn't fix the libuuid error.

> [21:25:49.772 I] OpenGL Vendor: NVIDIA Corporation
> [21:25:49.772 I] OpenGL Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
> [21:25:49.772 I] OpenGL Version: 4.6.0 NVIDIA 565.77
> [21:25:49.773 V] Available Extensions: 
> [21:25:49.773 *] Error [[21:25:49.773 *] GENERAL[21:25:49.773 *]  | [21:25:49.773 *] xrEnumerateInstanceExtensionProperties[21:25:49.773 *]  | [21:25:49.773 *] OpenXR-Loader[21:25:49.773 *] ] : [21:25:49.774 *] RuntimeInterface::LoadRuntime skipping manifest file /home/neko/.config/openxr/1/active_runtime.json, failed to load with message "libEGL.so.1: cannot open shared object file: No such file or directory"[21:25:49.774 *] 
> [21:25:49.774 *] Error [[21:25:49.774 *] GENERAL[21:25:49.774 *]  | [21:25:49.774 *] xrEnumerateInstanceExtensionProperties[21:25:49.774 *]  | [21:25:49.774 *] OpenXR-Loader[21:25:49.774 *] ] : [21:25:49.774 *] RuntimeInterface::LoadRuntimes - failed to load a runtime[21:25:49.774 *] 
> [21:25:49.774 *] Error [[21:25:49.774 *] GENERAL[21:25:49.774 *]  | [21:25:49.774 *] xrEnumerateInstanceExtensionProperties[21:25:49.774 *]  | [21:25:49.774 *] OpenXR-Loader[21:25:49.774 *] ] : [21:25:49.774 *] Failed to find default runtime with RuntimeInterface::LoadRuntime()[21:25:49.774 *] 
> [21:25:49.774 *] Error [[21:25:49.774 *] GENERAL[21:25:49.774 *]  | [21:25:49.774 *] xrEnumerateInstanceExtensionProperties[21:25:49.774 *]  | [21:25:49.774 *] OpenXR-Loader[21:25:49.774 *] ] : [21:25:49.774 *] Failed querying extension properties[21:25:49.774 *] 
> [21:25:49.774 E] /build/source/components/xr/extensions.cpp:173: OpenXR[Error: XR_ERROR_RUNTIME_UNAVAILABLE][Thread: 140321831673920]: xrEnumerateInstanceExtensionProperties(layerName, 0, &extensionCount, nullptr)
> [21:25:49.775 *] Error [[21:25:49.775 *] GENERAL[21:25:49.775 *]  | [21:25:49.775 *] xrEnumerateInstanceExtensionProperties[21:25:49.775 *]  | [21:25:49.775 *] OpenXR-Loader[21:25:49.775 *] ] : [21:25:49.775 *] RuntimeInterface::LoadRuntime skipping manifest file /home/neko/.config/openxr/1/active_runtime.json, failed to load with message "libEGL.so.1: cannot open shared object file: No such file or directory"[21:25:49.775 *] 
> [21:25:49.775 *] Error [[21:25:49.775 *] GENERAL[21:25:49.775 *]  | [21:25:49.775 *] xrEnumerateInstanceExtensionProperties[21:25:49.775 *]  | [21:25:49.775 *] OpenXR-Loader[21:25:49.775 *] ] : [21:25:49.775 *] RuntimeInterface::LoadRuntimes - failed to load a runtime[21:25:49.775 *] 
> [21:25:49.775 *] Error [[21:25:49.775 *] GENERAL[21:25:49.775 *]  | [21:25:49.775 *] xrEnumerateInstanceExtensionProperties[21:25:49.775 *]  | [21:25:49.775 *] OpenXR-Loader[21:25:49.775 *] ] : [21:25:49.775 *] Failed to find default runtime with RuntimeInterface::LoadRuntime()[21:25:49.775 *] 
> [21:25:49.775 *] Error [[21:25:49.775 *] GENERAL[21:25:49.775 *]  | [21:25:49.775 *] xrEnumerateInstanceExtensionProperties[21:25:49.775 *]  | [21:25:49.776 *] OpenXR-Loader[21:25:49.776 *] ] : [21:25:49.776 *] Failed querying extension properties[21:25:49.776 *] 
> [21:25:49.776 E] /build/source/components/xr/extensions.cpp:175: OpenXR[Error: XR_ERROR_RUNTIME_UNAVAILABLE][Thread: 140321831673920]: xrEnumerateInstanceExtensionProperties(layerName, availableExtensions.size(), &extensionCount, availableExtensions.data())
> [21:25:49.776 V] Available Layers: 
> [21:25:49.776 V]   No layers available
> [21:25:49.776 W] Warning: Failed to select OpenGL swapchains: OpenXR runtime does not support essential extension 'XR_KHR_opengl_enable'
> [21:25:49.776 V] Error: No graphics API supported by OpenMW VR is supported by the OpenXR runtime.
> [21:25:49.779 E] Error: Error: No graphics API supported by OpenMW VR is supported by the OpenXR runtime.

**Comment by numinit** [comment]
Are you missing a `lib`?

Try `export LD_LIBRARY_PATH=$(nix build --print-out-paths --no-link nixpkgs#libGL)/lib:$(nix build --print-out-paths --no-link nixpkgs#libuuid)/lib`. If that's it you'll need to use wrapProgram to set LD_LIBRARY_PATH in fixupPhase.

**Comment by bndlfm** [comment]
I've tried that but the libuuid part doesn't seem to take, not sure why.

Doesn't wrapProgram interfere with wrapQtAppsHook?

I'm investigating a way to append extra arguments to wrap with wrapQtAppsHook but I'm not sure of the syntax yet. Check out [https://nixos.wiki/wiki/Qt#Projects_using_python_.28e.g._PyQt5.29](https://nixos.wiki/wiki/Qt#Projects_using_python_.28e.g._PyQt5.29) and search for qtWrapperArgs

**Comment by numinit** [comment]
This is probably what you want then: https://ryantm.github.io/nixpkgs/languages-frameworks/qt/#qt-runtime-dependencies

**Comment by bndlfm** [comment]
fixed with qtWrapperArgs --prefix LD_LIBRARY_PRELOAD
