### ISSUE TITLE
substituteInPlace/sed instead of forking OpenXR-SDK

### ISSUE THREAD

**Issue by bndlfm** [bndlfm/OpenMW-VR_Nix#3]
This should be simple but I am unsure how to substitute/sed a dependency in a 'let .. in' block. Maybe ${openxr-sdk}/src/loader/openxr.pc.in ?

**Comment by numinit** [comment]
You're pulling down that source, I see... what do you need to do with it?

**Comment by bndlfm** [comment]
nix substitutes a path in the pc.in and there ends up being a // which it doesn't like

now it uses the upstream source w/ fetchFromGitHub.postFetch
